### ISSUE TITLE
Alarm ne radi pod Androidom 10

### ISSUE THREAD

**Issue by Irfy** [vaktija/vaktija.ba-android#1]
Selam/Pozdrav,

OnePlus 6T
Google Pixel 2
Google Pixel 3a

Niti na jednom od navedenih uredjaja sa Androidom 10 ne radi alarm, dok notifikacija i dalje radi. Ako je aplikacija ukljucena i aktivna u vrijeme kada se triggeruje alarm, onda radi.

U simulatoru alarm izgleda da radi.

**Comment by vaktija** [comment]
Alejkumusselam,

Hvala Vam za javljanje, u toku smo sa tim problemom, u Androidu v10 je bilo nekih izmjena pa je to uticalo ne samo na vaktiju.ba aplikaciju vec i na mnoge druge (https://developer.android.com/guide/components/activities/background-starts)

> Apps running on Android 10 or higher can start activities only when one or more of the following conditions are met:

Inace, radi(ce) se na rjesenju, a kada ce biti public jos nista ne mogu reci, trenutno nemamo raspolozive resurse kao na pocetku developmenta

p.s.
Mozete probati "fix" sa dev brancha (medjutim, to nece biti finalno rjesenje jer ce se raditi na drugom tipu rjesenja, koje ne podrazumjeva manuelno podesavanje permisija, aplikaciji nakon builda i install treba jos i permisija za overlay/on top, ja sam probavao na S10 i radi ok

https://github.com/vaktija/vaktija.ba-android/tree/dev
